- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  tasks:
    - import_tasks: tasks/pacman.yaml

    - import_tasks: tasks/ssh.yaml
    - import_tasks: tasks/fish.yaml
    - import_tasks: tasks/system.yaml

    - import_tasks: tasks/node.yaml
    - import_tasks: tasks/git.yaml
