- name: fish | install fish shell
  community.general.pacman:
      name: fish
      state: present

- name: fish | set fish as default shell
  become: true
  user:
      name: "{{ lookup('env', 'USER') }}"
      shell: /usr/bin/fish

- name: fish | set theme
  shell: fisher install catppuccin/fish & fish_config theme save "Catppuccin Mocha"
