- name: fish | install fish shell
  community.general.pacman:
    name: fish
    state: present

- name: fish | set fish as default shell
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/fish
